"""Shared order/fill value types for the strategy/risk/OMS core.

Frozen/slots dataclasses and ``StrEnum``s only — no I/O, no wall-clock reads,
no framework dependencies. These are the exact shapes shared unmodified
across backtest, paper, and live execution (CLAUDE.md §7.1): every consumer
(the Backtesting Engine's Fill_Model, a future paper-trading adapter, a
future live-trading adapter) imports these types rather than redefining or
forking them.

``OrderIntent`` is what a ``Strategy`` emits — a request to trade.
``Order`` is the broader, OMS-level representation of that intent once it
has been accepted for working (tracking cumulative fill progress), the same
shape backtest, paper, and live order-management logic operates on.
``Fill`` is a single simulated or real execution against an ``Order``.

All quantities and prices use ``Decimal`` for exact, reproducible arithmetic
(CLAUDE.md §5 — no floating-point ordering nondeterminism).
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from enum import StrEnum


class OrderSide(StrEnum):
    """The direction of an order or fill."""

    BUY = "buy"
    SELL = "sell"


class OrderType(StrEnum):
    """The order types supported by the shared OMS contracts."""

    MARKET = "market"
    LIMIT = "limit"


@dataclass(frozen=True, slots=True)
class OrderIntent:
    """A single target order emitted by a ``Strategy`` in response to an event.

    ``client_order_id`` is deterministically generated by the strategy/OMS
    logic so that re-processing the same event never produces a duplicate
    order (a requirement of the Backtesting Engine's determinism guarantee,
    and equally true for paper/live). ``emitted_at`` is derived from the
    caller's injected clock (the ``Simulation_Clock`` in a backtest, or the
    paper/live execution clock) — never wall-clock time read directly by
    this library.
    """

    client_order_id: str
    symbol: str
    side: OrderSide
    order_type: OrderType
    quantity: Decimal
    limit_price: Decimal | None
    emitted_at: datetime


@dataclass(frozen=True, slots=True)
class Order:
    """The broader, accepted/working order state tracked by the shared OMS logic.

    Represents an ``OrderIntent`` once it has passed the shared risk check
    and been accepted for working by the order-management logic. Unlike
    ``OrderIntent`` (a point-in-time request), ``Order`` tracks cumulative
    fill progress via ``filled_quantity`` and ``average_fill_price`` so that
    partial fills can be represented without a separate mutable order-status
    enum — callers derive "filled" / "partially filled" / "unfilled" from the
    relationship between ``quantity`` and ``filled_quantity``.

    ``order_id`` is the OMS-assigned identifier for the working order; it may
    equal ``client_order_id`` when no downstream system re-assigns one (as in
    a backtest), or differ from it when a paper/live venue assigns its own
    identifier.
    """

    order_id: str
    client_order_id: str
    symbol: str
    side: OrderSide
    order_type: OrderType
    quantity: Decimal
    limit_price: Decimal | None
    filled_quantity: Decimal
    average_fill_price: Decimal | None
    created_at: datetime

    @property
    def remaining_quantity(self) -> Decimal:
        """The quantity of this order not yet filled."""
        return self.quantity - self.filled_quantity

    @property
    def is_fully_filled(self) -> bool:
        """Whether this order has no remaining unfilled quantity."""
        return self.remaining_quantity <= Decimal(0)


@dataclass(frozen=True, slots=True)
class Fill:
    """A single execution (in whole or in part) of an ``Order``.

    ``filled_at`` is derived from the caller's injected clock, exactly as
    ``OrderIntent.emitted_at`` is — never a wall-clock read by this library.
    """

    client_order_id: str
    symbol: str
    side: OrderSide
    quantity: Decimal
    price: Decimal
    commission: Decimal
    filled_at: datetime
