"""Property + unit tests for the LocalArtifactStore adapter (task 8.8).

Exercises `adapters/local_artifact_store.py` in isolation: the write-then-read
round trip (Property 9), the deterministic path layout, and the never-overwrite
guarantee backed by `ArtifactAlreadyExistsError` (Requirements 7.6, 8.1, 8.2,
8.3). Each Hypothesis example gets its own fresh base directory (via
`tmp_path_factory.mktemp`) so repeated shrinking/replay of the never-overwrite
property never collides with artifacts left behind by a prior example.
"""

from __future__ import annotations

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from aqros_model_registry.adapters.local_artifact_store import LocalArtifactStore
from aqros_model_registry.domain.ports import ArtifactAlreadyExistsError

_model_names = st.text(
    alphabet=st.characters(whitelist_categories=("Ll", "Lu", "Nd"), whitelist_characters="_"),
    min_size=1,
    max_size=20,
)
_model_versions = st.integers(min_value=1, max_value=999)


def _fresh_store(tmp_path_factory: pytest.TempPathFactory) -> LocalArtifactStore:
    """Build a `LocalArtifactStore` rooted at a fresh temp directory.

    `tmp_path_factory` (session-scoped) is used instead of the function-scoped
    `tmp_path` fixture so each call — including every Hypothesis example within
    a single test function — gets its own clean directory. `tmp_path` is only
    created once per test function and would be reused across all examples
    generated by `@given`, which is exactly the cross-example interference the
    never-overwrite property must avoid.
    """
    return LocalArtifactStore(str(tmp_path_factory.mktemp("artifacts")))


# Feature: model-registry, Property 9: Artifact round-trip
# For any artifact persisted under (model_name, version), reading it back
# returns exactly the bytes written.
# Validates: Requirements 8.1, 8.2, 8.3
@settings(max_examples=100)
@given(
    model_name=_model_names,
    model_version=_model_versions,
    data=st.binary(max_size=256),
)
async def test_property_9_write_then_read_round_trip(
    model_name: str, model_version: int, data: bytes, tmp_path_factory: pytest.TempPathFactory
) -> None:
    store = _fresh_store(tmp_path_factory)
    await store.write_artifact(model_name, model_version, data)
    assert await store.read_artifact(model_name, model_version) == data


@settings(max_examples=100)
@given(model_name=_model_names, model_version=_model_versions)
async def test_write_artifact_uses_deterministic_path(
    model_name: str, model_version: int, tmp_path_factory: pytest.TempPathFactory
) -> None:
    base_dir = tmp_path_factory.mktemp("artifacts")
    store = LocalArtifactStore(str(base_dir))
    path = await store.write_artifact(model_name, model_version, b"payload")
    expected = base_dir / model_name / f"v{model_version}" / "model.joblib"
    assert path == str(expected)
    assert expected.exists()
    assert expected.read_bytes() == b"payload"


@settings(max_examples=100)
@given(model_name=_model_names, model_version=_model_versions)
async def test_second_write_to_same_key_never_overwrites(
    model_name: str, model_version: int, tmp_path_factory: pytest.TempPathFactory
) -> None:
    store = _fresh_store(tmp_path_factory)
    await store.write_artifact(model_name, model_version, b"original-bytes")

    with pytest.raises(ArtifactAlreadyExistsError):
        await store.write_artifact(model_name, model_version, b"replacement-bytes")

    assert await store.read_artifact(model_name, model_version) == b"original-bytes"


async def test_write_then_write_again_different_version_both_succeed(
    tmp_path: pytest.TempPathFactory,
) -> None:
    """Concrete example: distinct versions of the same model never collide."""
    store = LocalArtifactStore(str(tmp_path))
    await store.write_artifact("aapl_5d_direction__random_forest", 1, b"v1-bytes")
    await store.write_artifact("aapl_5d_direction__random_forest", 2, b"v2-bytes")

    assert await store.read_artifact("aapl_5d_direction__random_forest", 1) == b"v1-bytes"
    assert await store.read_artifact("aapl_5d_direction__random_forest", 2) == b"v2-bytes"


async def test_read_artifact_never_written_raises_file_not_found(
    tmp_path: pytest.TempPathFactory,
) -> None:
    store = LocalArtifactStore(str(tmp_path))
    with pytest.raises(FileNotFoundError):
        await store.read_artifact("never_registered__model", 1)
